### ISSUE TITLE
add "join mailing list" button

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/website#56]
http://eepurl.com/cjv1qj

**Comment by rphi** [comment]
Can we add any branding to that page? Also MailChimp supports embedded forms which might be worth taking a look at https://kb.mailchimp.com/lists/signup-forms/add-a-signup-form-to-your-website

**Comment by qaisjp** [comment]
are you thinking something like what we've done on hacktheburgh.com right now?

**Comment by rphi** [comment]
Maybe, yeah, just not linking through to the full MailChimp site might be nice? I think there is also a Modal form generator as well you could use (although I don't have anything using MailChimp so can't get to that)
